### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by desthon** [snoobi-seggs/AttackInfusedWithItem#3]
12:27:31 <INFO:PluginManager> 启用插件：AttackModifier
12:27:31 <ERROR:PluginManager> 无法启用插件：AttackModifier
java.lang.NoClassDefFoundError: emu/grasscutter/utils/EventConsumer
        at thorny.grasscutters.AttackModifier.AttackModifier.onEnable(AttackModifier.java:28)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:218)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:214)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:181)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.utils.EventConsumer
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 common frames omitted
12:27:31 <INFO:AttackModifier> Attack Modifier has been disabled.

**Comment by snoobi-seggs** [comment]
is coz they updated plugin loader on the main gc repo itself but i never update the plugin itself. also im lazi to fix this bruh ( = w =       )

**Comment by desthon** [comment]
so how to solve it? im not a pro

**Comment by snoobi-seggs** [comment]
idk eh, ask thoronium or smth he shld know (ehe)
